#Анализ нарушений московского метрополитена.

Задачи:
* Загрузить данные и познакомиться с ними;
* Предобработка данных и предварительное исследование;
* Исследовательский анализ;
* Формулировка выводов.

##1) Знакомство с датасетом

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
df = pd.read_excel('/metro.xlsx')

In [6]:
df.head()

,Начало случая,Окончание случая,"Перерыв в движении, мин",id станции,Станционный путь,Перегон,Кол-во опоздавших поездов,Кол-во минут опоздания,Кол-во полных отмен,Кол-во участковых отмен,Кол-во внеплановых высадок пассажиров,Линия,Ответственная служба,Тип нарушения,Причины возникновения,Наименование устройства,Наименование детали устройства,Общая причина возникновения
0,1974-01-01 00:00:00,2022-01-01 00:01:00,0,83.0,NaN,NaN,0,0,0,0,0,Кольцевая,ЭС,Остановка эскалатора из-за нарушения правил по...,Остановка эскалатора из-за нарушения правил по...,Эскалатор,NaN,Действия пассажиров
1,1974-01-01 00:01:00,2022-01-01 00:03:00,0,87.0,NaN,NaN,0,0,0,0,0,Кольцевая,ЭС,Остановка эскалатора ручкой СТОП пассажирами,Остановка эскалатора ручкой СТОП пассажирами,Эскалатор,NaN,Действия пассажиров
2,1974-01-01 00:06:00,2022-01-01 00:08:00,0,49.0,NaN,NaN,0,0,0,0,0,Бутовская,ЭС,Остановка эскалатора ручкой СТОП из-за угрозы ...,Остановка эскалатора ручкой СТОП из-за угрозы ...,Эскалатор,NaN,Действия пассажиров
3,1974-01-01 00:11:00,2022-01-01 00:13:00,0,274.0,NaN,NaN,0,0,0,0,0,Таганско-краснопресненская,ЭС,Остановка эскалатора ручкой СТОП из-за угрозы ...,Остановка эскалатора ручкой СТОП из-за угрозы ...,Эскалатор,NaN,Действия пассажиров
4,1974-01-01 00:13:00,2022-01-01 00:15:00,0,81.0,NaN,NaN,0,0,0,0,0,Кольцевая,ЭС,Падение пассажира на эскалаторе без травм,Падение пассажира на эскалаторе без травм,Эскалатор,Огибной участок,Действия пассажиров

In [7]:
df.columns = [col.lower().replace(' ', '_') for col in df.columns]

In [8]:
df.head()

,начало_случая,окончание_случая,"перерыв_в_движении,_мин",id_станции,станционный_путь,перегон,кол-во_опоздавших_поездов,кол-во_минут_опоздания,кол-во_полных_отмен,кол-во_участковых_отмен,кол-во_внеплановых_высадок_пассажиров,линия,ответственная_служба,тип_нарушения,причины_возникновения,наименование_устройства,наименование_детали_устройства,общая_причина_возникновения
0,1974-01-01 00:00:00,2022-01-01 00:01:00,0,83.0,NaN,NaN,0,0,0,0,0,Кольцевая,ЭС,Остановка эскалатора из-за нарушения правил по...,Остановка эскалатора из-за нарушения правил по...,Эскалатор,NaN,Действия пассажиров
1,1974-01-01 00:01:00,2022-01-01 00:03:00,0,87.0,NaN,NaN,0,0,0,0,0,Кольцевая,ЭС,Остановка эскалатора ручкой СТОП пассажирами,Остановка эскалатора ручкой СТОП пассажирами,Эскалатор,NaN,Действия пассажиров
2,1974-01-01 00:06:00,2022-01-01 00:08:00,0,49.0,NaN,NaN,0,0,0,0,0,Бутовская,ЭС,Остановка эскалатора ручкой СТОП из-за угрозы ...,Остановка эскалатора ручкой СТОП из-за угрозы ...,Эскалатор,NaN,Действия пассажиров
3,1974-01-01 00:11:00,2022-01-01 00:13:00,0,274.0,NaN,NaN,0,0,0,0,0,Таганско-краснопресненская,ЭС,Остановка эскалатора ручкой СТОП из-за угрозы ...,Остановка эскалатора ручкой СТОП из-за угрозы ...,Эскалатор,NaN,Действия пассажиров
4,1974-01-01 00:13:00,2022-01-01 00:15:00,0,81.0,NaN,NaN,0,0,0,0,0,Кольцевая,ЭС,Падение пассажира на эскалаторе без травм,Падение пассажира на эскалаторе без травм,Эскалатор,Огибной участок,Действия пассажиров